[tool.poetry]
name = "shine"
version = "0.1.0"
description = "A solver library for mathematical and computational problems"
authors = ["Jonathan Palafoutas <jpalafou@princeton.edu>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jpalafou/shine"
# homepage = ...

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
rationalpy = "*"
"stencilpal" = { git = "https://github.com/jpalafou/stencilpal", rev = "0.1.0" }

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

# [tool.poetry.urls]
# documentation = "https://yourprojectdocumentation.com"

# Optional: Define additional configurations for packaging, building, etc.
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
