[tool.poetry]
name = "superfv"
version = "0.1.0"
description = "A solver library for mathematical and computational problems"
authors = ["Jonathan Palafoutas <jpalafou@princeton.edu>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jpalafou/superfv"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "*"
numpy = "*"
rationalpy = "*"
stencilpal = { git = "https://github.com/jpalafou/stencilpal" }
tqdm = "*"

[tool.poetry.group.dev.dependencies]
nox = "*"
pre-commit = "*"

[tool.poetry.group.typecheck.dependencies]
mypy = "*"
types-tqdm = "*"

[tool.poetry.group.test.dependencies]
"pandas" = "*"
pytest="*"

[tool.mypy]
mypy_path = "stubs"
