name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "Poetry installed at $(which poetry)"

      - name: Install dependencies with Poetry
        run: |
          poetry lock
          poetry install --with dev --with test

      - name: Run Nox test session
        run: |
          poetry run nox -s test

  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "Poetry installed at $(which poetry)"

      - name: Install dependencies with Poetry
        run: |
          poetry lock
          poetry install --with dev --with typecheck

      - name: Run Nox lint session
        run: |
          poetry run nox -s lint

      - name: Run Nox typecheck session
        run: |
          poetry run nox -s typecheck
